### ISSUE TITLE
incorrect attachment reporting

### ISSUE THREAD

**Issue by jkroonza** [svarshavchik/courier-libs#38]
We've got one user who is being a pain about this, Outlook 16, courier-imap (5.2.5).

When replying to emails, which has images in signatures (ie, inline attachments), then, if using IMAP, the mail item in .Sent (or items or wherever they go) will report in the list of sent emails as having an attachment.

I've checked the encoding of the emails, and the html parts are all quoted-printable transfer encoded in the email file, and the html portion uses utf-8 encoding.

I'm convinced it has to be an Outlook issue, but I recall I've seen similar in Thunderbird previously as well, but it clears once I've displauyed the email, which made me wonder if IMAP initially reports which emails has attachments and which not, and TB then realizes the mistake and corrects whereas Outlook does not?

Ideas/suggestions?

**Comment by svarshavchik** [comment]
There's no such thing as "attachments" in IMAP. IMAP merely reports what's called the messages "MIME structure", which includes the "Content Type" of a message's every MIME entity.

The IMAP server has no means to determine whether the IMAP client "displayed" something, or not. It merely reports a message's MIME structure. The response should always be the same.

Both messages with inline images and messages with formal attachments are messages with multiple MIME sections. Sounds like Outlook is too dumb to figure out the difference. But that's something that the server has no control over. An IMAP client should be able to tell the difference between ["multipart/related" MIME content](https://www.ietf.org/rfc/rfc2387.txt) (HTML with inline images) and ["multipart/mixed MIME content](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) (ordinarya attachments).

Of course, it's also possible that the sending software is broken, and the MIME message is not correctly formatted. It's impossible to conclusively say without inspecting the actual message; but that would agree with your second observation: the message's MIME type is wrong, it's "multipart/mixed" instead of "multipart/related". The IMAP server correctly reports its MIME type, and the IMAP client shows it as having attachments; but after loading the message's content and parsing it it realizes that every MIME entity in the message is linked inline from the main MIME entity's HTML content, and there are no actual attachments.

The server cannot do anything about it, it only reports what the message's MIME structure is.

**Comment by jkroonza** [comment]
@svarshavchik thanks for confirming my understanding.
